language: csharp
solution: SeleniumBasics.sln
notifications:
  slack: de-labs:Sch4Zt9sxr8XiPi7ltIFSm5p
mono: latest
before_install:
  - sudo apt-get install nunit-console
before_script:
  - nuget restore SeleniumBasics.sln
script: 
  - msbuild /p:Configuration=Release SeleniumBasics.sln
after_script:
  - nunit-console SeleniumBasics/bin/Release/SeleniumBasics.dll
